/// Generated by AssetsRefGenerator on 2021/10/25
class Res {
  static const String incognito = "assets/incognito-icon.jpg";
  static const String gear = "assets/gear.png";
  static const String help = "assets/help.png";
  static const String home = "assets/home.png";
  static const String home_1 = "assets/home-1.png";
  static const String icon_aset = "assets/icon_aset.png";
  static const String icon_profile = "assets/icon_profile.png";
  static const String icon_sewaan = "assets/icon_sewaan.png";
  static const String icon_utama = "assets/icon_utama.png";
  static const String image5 = "assets/image5.png";
  static const String image_logo = "assets/image_logo.png";
  static const String image_pasar_a = "assets/image_pasar_a.png";
  static const String image_pasar_b = "assets/image_pasar_b.png";
  static const String image_pasar_d = "assets/image_pasar_d.png";
  static const String invoice = "assets/invoice.png";
  static const String kopi = "assets/kopi.jpg";
  static const String ms = "assets/lang/ms.json";
  static const String profil_pasar_a = "assets/profil_pasar_a.png";
  static const String sample = "assets/sample.pdf";
  static const String upload = "assets/upload.png";
  static const String user = "assets/user.png";
  static const String faq1 = "assets/f1.jpg";
  static const String faq2 = "assets/f2.jpg";
  static const String faq3 = "assets/f3.jpg";
}
